import streamlit as st
import random

# Your word list
words = [
{"word": "Africa", "meaning": "A continent", "sentence": "We studied animals in Africa.", "emoji": "🌍"},
    {"word": "appear", "meaning": "To come into view", "sentence": "Stars appear at night.", "emoji": "✨"},
    {"word": "angle", "meaning": "The space between two lines", "sentence": "The angle of the roof is steep.", "emoji": "📐"},
    {"word": "bear", "meaning": "A large wild animal", "sentence": "A bear lives in the forest.", "emoji": "🐻"},
    {"word": "bright", "meaning": "Very full of light", "sentence": "The sun is bright today.", "emoji": "☀️"},
    {"word": "broken", "meaning": "Not working or in pieces", "sentence": "The toy is broken.", "emoji": "🧸"},
    {"word": "build", "meaning": "To make something", "sentence": "We build sandcastles at the beach.", "emoji": "🏖️"},
    {"word": "century", "meaning": "One hundred years", "sentence": "A century is a long time.", "emoji": "📅"},
    {"word": "consonant", "meaning": "A speech sound that is not a vowel", "sentence": "B is a consonant.", "emoji": "🔤"},
    {"word": "dictionary", "meaning": "Book that gives word meanings", "sentence": "She looked up the word in a dictionary.", "emoji": "📘"},
    {"word": "exactly", "meaning": "Completely correct", "sentence": "You got the answer exactly right!", "emoji": "✔️"},
    {"word": "factors", "meaning": "Numbers that multiply to a product", "sentence": "We found all factors of 12.", "emoji": "➗"},
    {"word": "fraction", "meaning": "Part of a whole", "sentence": "Half is a fraction.", "emoji": "½"},
    {"word": "metal", "meaning": "Hard solid material like iron", "sentence": "The handle is made of metal.", "emoji": "⚙️"},
    {"word": "method", "meaning": "A way of doing something", "sentence": "We used a new method to solve it.", "emoji": "🧠"},
    {"word": "melody", "meaning": "A tune or song", "sentence": "That melody sounds happy.", "emoji": "🎶"},
    {"word": "moment", "meaning": "A very short time", "sentence": "Wait a moment, please.", "emoji": "⏳"},
    {"word": "natural", "meaning": "In nature, not made by humans", "sentence": "The wood has a natural smell.", "emoji": "🌿"},
    {"word": "possible", "meaning": "Able to happen", "sentence": "It’s possible to win with practice.", "emoji": "🏆"},
    {"word": "quiet", "meaning": "Making very little noise", "sentence": "Please be quiet in the library.", "emoji": "🤫"},
    {"word": "quite", "meaning": "Very or actually", "sentence": "That was quite fun!", "emoji": "😄"},
    {"word": "remain", "meaning": "To stay in the same place", "sentence": "Only five cookies remain.", "emoji": "🍪"},
    {"word": "surprise", "meaning": "Something unexpected", "sentence": "That was a nice surprise!", "emoji": "🎁"},
    {"word": "temperature", "meaning": "How hot or cold something is", "sentence": "The temperature is cold today.", "emoji": "🌡️"},
    {"word": "weather", "meaning": "What it’s like outside (rain, sun)", "sentence": "The weather is sunny.", "emoji": "☀️"},
    {"word": "village", "meaning": "A very small town", "sentence": "They visit a village in the hills.", "emoji": "🏘️"},
    {"word": "within", "meaning": "Inside or not beyond", "sentence": "Stay within the fence.", "emoji": "⬜"},
    {"word": "wonder", "meaning": "To think or feel curious", "sentence": "I wonder about space.", "emoji": "🤔"},
    {"word": "already", "meaning": "Before now", "sentence": "We have already eaten.", "emoji": "✅"},
    {"word": "although", "meaning": "But, even though", "sentence": "Although it rained, we played.", "emoji": "🌧️"},
    {"word": "amount", "meaning": "Quantity or number", "sentence": "She added a large amount of sugar.", "emoji": "🍬"},
    {"word": "appear", "meaning": "To show up", "sentence": "The moon appears at night.", "emoji": "🌙"},
    {"word": "country", "meaning": "A nation of people", "sentence": "India is a country.", "emoji": "🌏"},
    {"word": "cross", "meaning": "To go from one side to another", "sentence": "Cross the bridge carefully.", "emoji": "🌉"},
    {"word": "exactly", "meaning": "Precisely right", "sentence": "That is exactly what I meant.", "emoji": "🎯"},
    {"word": "free", "meaning": "Costing nothing", "sentence": "The toy was free.", "emoji": "🎈"},
    {"word": "gold", "meaning": "A yellow precious metal", "sentence": "The medal is made of gold.", "emoji": "🏅"},
    {"word": "hill", "meaning": "A small mountain", "sentence": "We climbed a hill.", "emoji": "⛰️"},
    {"word": "hole", "meaning": "An empty space", "sentence": "The rabbit dug a hole.", "emoji": "🕳️"},
    {"word": "hope", "meaning": "To wish for something", "sentence": "I hope we win.", "emoji": "🙏"},
    {"word": "instead", "meaning": "In its place", "sentence": "Use water instead of juice.", "emoji": "🚰"},
    {"word": "iron", "meaning": "Strong metal", "sentence": "The gate is made of iron.", "emoji": "🧲"},
    {"word": "lake", "meaning": "Body of water surrounded by land", "sentence": "The fish live in the lake.", "emoji": "🏞️"},
    {"word": "laughed", "meaning": "Past of laugh", "sentence": "She laughed at the joke.", "emoji": "😆"},
    {"word": "lead", "meaning": "To go before others", "sentence": "She will lead the group.", "emoji": "🚩"},
    {"word": "lot", "meaning": "Many or much", "sentence": "A lot of birds flew by.", "emoji": "🐦"},
    {"word": "middle", "meaning": "Center part", "sentence": "He stood in the middle.", "emoji": "⚖️"},
    {"word": "moment", "meaning": "Short period of time", "sentence": "Wait a moment!", "emoji": "⏲️"},
    {"word": "method", "meaning": "Procedure or way", "sentence": "This method works well.", "emoji": "📝"},
    {"word": "nation", "meaning": "Country", "sentence": "Dogs live in every nation.", "emoji": "🌐"},
    {"word": "natural", "meaning": "Inherent or native", "sentence": "The natural scent was strong.", "emoji": "🌱"},
    {"word": "outside", "meaning": "Not inside", "sentence": "Play outside with friends.", "emoji": "🏀"},
    {"word": "phrase", "meaning": "Short group of words", "sentence": "Repeat the phrase after me.", "emoji": "✏️"},
    {"word": "possible", "meaning": "Able to happen", "sentence": "It’s possible to learn fast.", "emoji": "📘"},
    {"word": "quiet", "meaning": "Very calm or silent", "sentence": "The room is very quiet.", "emoji": "🤫"},
    {"word": "ride", "meaning": "To travel on something", "sentence": "Ride the bike carefully.", "emoji": "🚲"},
    {"word": "scale", "meaning": "Device for weighing", "sentence": "Use the scale to weigh fruit.", "emoji": "⚖️"},
    {"word": "section", "meaning": "A separate part", "sentence": "Read the next section.", "emoji": "📄"},
    {"word": "smiled", "meaning": "Showed happiness", "sentence": "She smiled at me.", "emoji": "😊"},
    {"word": "snow", "meaning": "Frozen precipitation", "sentence": "Snow covers the ground.", "emoji": "❄️"},
    {"word": "solve", "meaning": "Find the answer", "sentence": "Solve the puzzle together.", "emoji": "🧩"},
    {"word": "someone", "meaning": "An unspecified person", "sentence": "Someone called your name.", "emoji": "👤"},
    {"word": "speed", "meaning": "How fast something moves", "sentence": "The car’s speed is high.", "emoji": "🏎️"},
    {"word": "spring", "meaning": "The season after winter", "sentence": "Flowers bloom in spring.", "emoji": "🌷"},
    {"word": "stone", "meaning": "A small rock", "sentence": "He skipped a stone.", "emoji": "🪨"},
    {"word": "tall", "meaning": "Having great height", "sentence": "The tree is very tall.", "emoji": "🌳"},
    {"word": "temperature", "meaning": "Degree of hot or cold", "sentence": "Check the temperature outside.", "emoji": "🌤️"},
    {"word": "themselves", "meaning": "Referring to them", "sentence": "They did it themselves.", "emoji": "🧒🧒"},
    {"word": "tiny", "meaning": "Very small", "sentence": "The kitten is tiny.", "emoji": "🐾"},
    {"word": "trip", "meaning": "Journey or travel", "sentence": "We took a trip to the zoo.", "emoji": "🦓"},
    {"word": "type", "meaning": "Kind or sort", "sentence": "What type of fruit do you like?", "emoji": "🍍"},
    {"word": "village", "meaning": "Small community", "sentence": "They live in a small village.", "emoji": "🏡"},
    {"word": "within", "meaning": "Inside a limit", "sentence": "Stay within the line.", "emoji": "🟥"},
    {"word": "wonder", "meaning": "To be curious about", "sentence": "I wonder how birds fly.", "emoji": "🐦"},
    {"word": "Assassination", "meaning": "The act of killing someone important secretly", "sentence": "The assassination of the king shocked the kingdom.", "emoji": "🗡️"},
    {"word": "Reticent", "meaning": "Not willing to talk or share thoughts", "sentence": "He was reticent about his past.", "emoji": "🤐"},
    {"word": "Shriveling", "meaning": "Becoming wrinkled or dry", "sentence": "The leaves were shriveling in the sun.", "emoji": "🍂"},
    {"word": "Stooping", "meaning": "Bending your body forward or downward", "sentence": "Grandpa walked slowly, stooping a little.", "emoji": "🧓"},
    {"word": "Streams", "meaning": "Small, flowing bodies of water", "sentence": "Streams flowed through the quiet forest.", "emoji": "🌊"},
    {"word": "Petulant", "meaning": "Being grumpy or easily annoyed", "sentence": "The petulant child crossed his arms and pouted.", "emoji": "😠"},
    {"word": "Pace", "meaning": "The speed at which someone moves", "sentence": "She walked at a fast pace.", "emoji": "🚶‍♀️"},
    {"word": "Yearning", "meaning": "A strong desire or longing", "sentence": "He had a yearning to visit the stars.", "emoji": "🌌"},
]

st.set_page_config(page_title="Word of the Day for Kids", page_icon="📚")

st.title("📚 Word of the Day for Kids")
st.markdown("Click the button to learn a new word!")

if st.button("🔁 Show New Word"):
    word = random.choice(words)
    st.subheader(f"{word['word']} {word['emoji']}")
    st.write(f"**Meaning:** {word['meaning']}")
    st.write(f"**Sentence:** _{word['sentence']}_")